# Training the model

In [1]:
import pickle

In [2]:
x = pickle.load(open('x.pk1', 'rb'))             # loading the pickle file
y = pickle.load(open('y.pk2', 'rb'))

In [3]:
x                                               # read value in a arry in  pixcel form (R,G,B)
                                                # reach value in between 0 - 255 

array([[[117, 116, 117, ...,  95,  96, 101],
        [125, 119, 109, ..., 105, 101,  98],
        [107, 107, 102, ..., 101, 100, 100],
        ...,
        [157, 155, 155, ..., 128, 133, 133],
        [121, 134, 135, ..., 135, 126, 143],
        [139, 126, 119, ..., 123, 130, 130]],

       [[133, 132, 133, ..., 142, 137, 140],
        [136, 137, 137, ..., 147, 144, 145],
        [134, 139, 142, ..., 146, 148, 147],
        ...,
        [211, 218, 223, ..., 243, 235, 239],
        [212, 221, 215, ..., 240, 243, 243],
        [217, 222, 222, ..., 245, 237, 242]],

       [[ 95,  96,  80, ...,  18,  48,  37],
        [ 68,  55,  95, ...,  46,  60,  55],
        [ 71,  68,  48, ...,  48,  41,  27],
        ...,
        [ 85,  87,  89, ..., 149, 145, 121],
        [ 72,  78,  76, ..., 155, 121, 131],
        [ 67,  67,  65, ..., 128, 136, 124]],

       ...,

       [[ 44,  45,  52, ...,  36,  33,  31],
        [ 45,  46,  51, ...,  36,  34,  32],
        [ 46,  48,  51, ...,  36,  34,  32

In [4]:
y     # y values in form of 0 and 1  ..0(cat), 1(dog)

array([1, 0, 1, ..., 0, 0, 0])

In [5]:
# feature scalling helps in calculating and running a model in a faster way

x = x/255

In [6]:
x   # all valus converts 0 to 1

array([[[0.45882353, 0.45490196, 0.45882353, ..., 0.37254902,
         0.37647059, 0.39607843],
        [0.49019608, 0.46666667, 0.42745098, ..., 0.41176471,
         0.39607843, 0.38431373],
        [0.41960784, 0.41960784, 0.4       , ..., 0.39607843,
         0.39215686, 0.39215686],
        ...,
        [0.61568627, 0.60784314, 0.60784314, ..., 0.50196078,
         0.52156863, 0.52156863],
        [0.4745098 , 0.5254902 , 0.52941176, ..., 0.52941176,
         0.49411765, 0.56078431],
        [0.54509804, 0.49411765, 0.46666667, ..., 0.48235294,
         0.50980392, 0.50980392]],

       [[0.52156863, 0.51764706, 0.52156863, ..., 0.55686275,
         0.5372549 , 0.54901961],
        [0.53333333, 0.5372549 , 0.5372549 , ..., 0.57647059,
         0.56470588, 0.56862745],
        [0.5254902 , 0.54509804, 0.55686275, ..., 0.57254902,
         0.58039216, 0.57647059],
        ...,
        [0.82745098, 0.85490196, 0.8745098 , ..., 0.95294118,
         0.92156863, 0.9372549 ],
        [0.8

In [7]:
x.shape    # 23000 is no if images , 60= width , 60 = hight , 3 = chanels R,G,B

(23000, 60, 60)

In [8]:
x = x.reshape(-1, 60, 60, 1)

In [11]:
import keras

Using TensorFlow backend.


In [9]:

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

Using TensorFlow backend.


##  Devloping model

 ### Design model

In [13]:
model = Sequential()


# add first convulutaion n/w total 2 convulution layer added here written same codde two types

model.add(Conv2D(64,(3,3), activation = 'relu'))  # 64=filters or feature detector, 3,3 = matrixs, relu is activation function 
model.add(MaxPooling2D((2,2)))                    # adding maxpooling 

model.add(Conv2D(64,(3,3), activation = 'relu'))  
model.add(MaxPooling2D((2,2)))


# Fltten
model.add(Flatten())

# one heden layer with 128 nuerons , x.shape [1:] means (23000, 100, 100, 3) considering from 100 to all
model.add(Dense(128, input_shape = x.shape [1:], activation = 'relu'))  


# output layer  2 nurons for cat and dog
model.add(Dense(2, activation = 'softmax'))   



In [14]:
# add loss functions and optimizer 
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [15]:
# Fit the model             Validation_split = part of the data is taken for validation
model.fit(x, y, epochs = 5, validation_split = 0.1 ) 





Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 20700 samples, validate on 2300 samples
Epoch 1/5





20700/20700 [==============================] - 102s 5ms/step - loss: 0.6367 - acc: 0.6296 - val_loss: 0.5494 - val_acc: 0.7239
Epoch 2/5
20700/20700 [==============================] - 104s 5ms/step - loss: 0.5248 - acc: 0.7396 - val_loss: 0.5023 - val_acc: 0.7500
Epoch 3/5
20700/20700 [==============================] - 104s 5ms/step - loss: 0.4674 - acc: 0.7748 - val_loss: 0.4987 - val_acc: 0.7543
Epoch 4/5
20700/20700 [==============================] - 106s 5ms/step - loss: 0.4115 - acc: 0.8100 - val_loss: 0.4546 - val_acc: 0.7748
Epoch 5/5
20700/20700 [==============================] - 103s 5ms/step - loss: 0.3562 - acc: 0.8405 - val_loss: 0.4351 - val_acc: 0.8000


In [ ]:
#  accurecy is 84% and the val-accuracy = 80% 
# both accurecy and val-accuracy  should not have much of deviation, if much deviation then 
# tunning procedure will take further

In [17]:
x.shape

(23000, 60, 60, 1)

In [18]:
import time

time.time()

1627300348.9172175

In [19]:
type(1581428129.5990093)

float

In [ ]:
model.summary()

In [19]:
#from tensorflow.keras.models import load_model

#model.save('model_cat_dog.h5')

In [36]:
#from tensorflow.keras.models import load_model
 
# load model
#model = load_model('model_cat_dog.h5')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [53]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 58, 58, 64)        640       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 29, 29, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 27, 27, 64)        36928     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 13, 13, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 10816)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               1384576   
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 258       
Total para

In [54]:
model.save('3x3x64-catvsdog.model')